@baseUrl = http://localhost:8080
@roomId = {{createRoom.response.body.id}}
@token1 = {{createMatch.response.body.playerTokens.0}}
@token2 = {{createMatch.response.body.playerTokens.1}}


### Get Catalog
GET http://localhost:8080/api/catalog
Content-Type: application/json


### Create Room
# @name createRoom
POST {{baseUrl}}/api/match-rooms


### Create Match
# @name createMatch
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match
Content-Type: application/json

{
  "gameCfg": {
    "stagePreset": "Plain",
    "p1Teams": ["King", "Fighter", "Fighter", "Witch", "Bandit"],
    "p2Teams": ["King", "Witch", "Fighter", "Bandit", "Bandit"],
    "maxTurns": 30,
    "allowResetTurn": true,
  }
}


### Get State
GET {{baseUrl}}/api/match-rooms/{{roomId}}/match/state


### Turn Command (move)
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/turn-commands
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "type": "move",
  "unitId": 16,
  "target": {
    "x": 4,
    "y": 7
  }
}


### Turn Command (placeBomb)
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/turn-commands
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "type": "placeBomb",
  "unitId": 16,
  "target": {
    "x": 4,
    "y": 5
  }
}


### Start Turn
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/start-turn
Authorization: Bearer {{token1}}


### Reset Turn
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/reset
Authorization: Bearer {{token1}}


### Resolve
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/resolve
Authorization: Bearer {{token1}}


### Surrender
POST {{baseUrl}}/api/match-rooms/{{roomId}}/match/surrender
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "teamId": 1
}


### Get Match Config
GET {{baseUrl}}/api/match-rooms/{{roomId}}/match/config


### Get Allowed Tiles
GET {{baseUrl}}/api/match-rooms/{{roomId}}/match/allowed-tiles?unitId=16&turnCmdType=placeBomb