name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to post the coverage table to your PR chat
      contents: write      # Required to save and compare baseline coverage files
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Run unit tests with coverage
      run: go test -v -coverprofile=cover.out ./...

    - name: Post Coverage Report to PR
      uses: fgrosse/go-coverage-report@v1.2.0
